--f5a77a1cb374caa5bad2b406c76afbbb97a27d8f2f585110aa62f4774ad6
Content-Disposition: form-data; name="worker.js"

const GAS_URL = "https://script.google.com/macros/s/AKfycbwt80iNeRz50rWWtYE8cvqb9PcQcHeB5jwGD92Iu5l1rgffH2YUbRSqRMDO2LM7p6fN/exec";
const LIFF_ID = "2010069897-X9JY7R2h";

export default {
  async fetch(request, env, ctx) {

      // GET = LIFF フォーム画面を配信
          if (request.method === "GET") {
                let categories = [];
                      try {
                              const res = await fetch(GAS_URL + "?action=getCategories", { redirect: "follow" });
                                      if (res.ok) categories = await res.json();
                                            } catch (err) {
                                                    console.log("categories fetch error:", err);
                                                          }

                                                                // 日本時間で現在月を取得
                                                                      const tokyoDate = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Tokyo" }));
                                                                            const currentMonth = tokyoDate.getMonth() + 1;

                                                                                  const html = buildFormHtml(categories, currentMonth);
                                                                                        return new Response(html, {
                                                                                                headers: { "Content-Type": "text/html; charset=utf-8" }
                                                                                                      });
                                                                                                          }

                                                                                                              // POST = LINE Webhook の中継（既存通り）
                                                                                                                  const body = await request.text();
                                                                                                                      ctx.waitUntil(
                                                                                                                            fetch(GAS_URL, {
                                                                                                                                    method: "POST",
                                                                                                                                            headers: { "Content-Type": "application/json" },
                                                                                                                                                    body: body,
                                                                                                                                                            redirect: "follow"
                                                                                                                                                                  }).catch(err => console.log(err))
                                                                                                                                                                      );
                                                                                                                                                                          return new Response("OK", { status: 200 });
                                                                                                                                                                            }
                                                                                                                                                                            };

                                                                                                                                                                            function buildFormHtml(categories, currentMonth) {
                                                                                                                                                                              const catJson = JSON.stringify(categories);
                                                                                                                                                                                const catOptions = categories.map(c =>
                                                                                                                                                                                    `<option value="${c.name}" data-needs-payment="${c.needsPayment}">${c.name}</option>`
                                                                                                                                                                                      ).join('\n      ');

                                                                                                                                                                                        return `<!DOCTYPE html>
                                                                                                                                                                                        <html lang="ja">
                                                                                                                                                                                        <head>
                                                                                                                                                                                        <meta charset="UTF-8">
                                                                                                                                                                                        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
                                                                                                                                                                                        <script charset="utf-8" src="https://static.line-scdn.net/liff/edge/2/sdk.js"></` + `script>
                                                                                                                                                                                        <style>
                                                                                                                                                                                        * { box-sizing: border-box; margin: 0; padding: 0; -webkit-tap-highlight-color: transparent; }
                                                                                                                                                                                        body { font-family: -apple-system, BlinkMacSystemFont, 'Hiragino Sans', 'Yu Gothic UI', sans-serif; background: #f0f2f5; min-height: 100vh; }
                                                                                                                                                                                        .header { background: #00B900; color: white; padding: 14px 16px; font-size: 17px; font-weight: bold; text-align: center; letter-spacing: 0.5px; position: sticky; top: 0; z-index: 10; }
                                                                                                                                                                                        .form-wrap { padding: 14px 14px 100px; max-width: 520px; margin: 0 auto; }
                                                                                                                                                                                        .card { background: white; border-radius: 14px; padding: 16px; margin-bottom: 12px; box-shadow: 0 1px 4px rgba(0,0,0,0.09); }
                                                                                                                                                                                        .label { font-size: 11px; color: #999; font-weight: bold; letter-spacing: 0.8px; text-transform: uppercase; margin-bottom: 10px; }
                                                                                                                                                                                        .month-nav { display: flex; align-items: center; justify-content: space-between; }
                                                                                                                                                                                        .month-arrow { width: 40px; height: 40px; border: none; background: #f0f2f5; border-radius: 50%; font-size: 20px; color: #00B900; cursor: pointer; display: flex; align-items: center; justify-content: center; }
                                                                                                                                                                                        .month-arrow:active { background: #e0f5e0; }
                                                                                                                                                                                        .month-display { font-size: 26px; font-weight: bold; color: #222; }
                                                                                                                                                                                        select { width: 100%; padding: 13px 12px; font-size: 16px; border: 1.5px solid #e8e8e8; border-radius: 10px; background: #fafafa; appearance: none; -webkit-appearance: none; background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%23999' stroke-width='1.5' fill='none'/%3E%3C/svg%3E"); background-repeat: no-repeat; background-position: right 14px center; }
                                                                                                                                                                                        select:focus { border-color: #00B900; outline: none; background-color: #fff; }
                                                                                                                                                                                        input[type=text], input[type=number] { width: 100%; padding: 13px 12px; font-size: 16px; border: 1.5px solid #e8e8e8; border-radius: 10px; background: #fafafa; }
                                                                                                                                                                                        input:focus { border-color: #00B900; outline: none; background: #fff; }
                                                                                                                                                                                        .payment-row { display: flex; gap: 10px; }
                                                                                                                                                                                        .pay-btn { flex: 1; padding: 13px 8px; border: 2px solid #e8e8e8; border-radius: 10px; background: #fafafa; font-size: 15px; cursor: pointer; text-align: center; transition: all 0.15s; color: #555; }
                                                                                                                                                                                        .pay-btn.active { border-color: #00B900; background: #e8f5e9; color: #00B900; font-weight: bold; }
                                                                                                                                                                                        .pay-btn:active { opacity: 0.7; }
                                                                                                                                                                                        .footer-bar { position: fixed; bottom: 0; left: 0; right: 0; padding: 12px 16px; padding-bottom: calc(12px + env(safe-area-inset-bottom)); background: white; border-top: 1px solid #eee; }
                                                                                                                                                                                        .submit-btn { width: 100%; padding: 15px; background: #00B900; color: white; border: none; border-radius: 12px; font-size: 17px; font-weight: bold; cursor: pointer; letter-spacing: 0.5px; }
                                                                                                                                                                                        .submit-btn:disabled { background: #bbb; }
                                                                                                                                                                                        .submit-btn:active { background: #009900; }
                                                                                                                                                                                        #successView { display: none; flex-direction: column; align-items: center; justify-content: center; min-height: 60vh; padding: 40px 20px; }
                                                                                                                                                                                        .success-icon { font-size: 72px; margin-bottom: 20px; }
                                                                                                                                                                                        .success-text { font-size: 22px; font-weight: bold; color: #222; margin-bottom: 8px; }
                                                                                                                                                                                        .success-sub { font-size: 14px; color: #888; }
                                                                                                                                                                                        </style>
                                                                                                                                                                                        </head>
                                                                                                                                                                                        <body>
                                                                                                                                                                                        <div class="header">📒 家計簿入力</div>
                                                                                                                                                                                        <div class="form-wrap" id="mainForm">
                                                                                                                                                                                          <div class="card">
                                                                                                                                                                                              <div class="label">月</div>
                                                                                                                                                                                                  <div class="month-nav">
                                                                                                                                                                                                        <button class="month-arrow" onclick="changeMonth(-1)">‹</button>
                                                                                                                                                                                                              <div class="month-display" id="monthDisplay">${currentMonth}月</div>
                                                                                                                                                                                                                    <button class="month-arrow" onclick="changeMonth(1)">›</button>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                            <div class="card">
                                                                                                                                                                                                                                <div class="label">項目</div>
                                                                                                                                                                                                                                    <select id="category" onchange="onCategoryChange()">
                                                                                                                                                                                                                                          <option value="">選択してください</option>
                                                                                                                                                                                                                                                ${catOptions}
                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                        <div class="card" id="paymentCard" style="display:none">
                                                                                                                                                                                                                                                            <div class="label">支払方法</div>
                                                                                                                                                                                                                                                                <div class="payment-row">
                                                                                                                                                                                                                                                                      <div class="pay-btn" id="btn-cash" onclick="selectPayment('キャッシュ')">💴 現金</div>
                                                                                                                                                                                                                                                                            <div class="pay-btn" id="btn-card" onclick="selectPayment('カード')">💳 カード</div>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                    <div class="card">
                                                                                                                                                                                                                                                                                        <div class="label">内容</div>
                                                                                                                                                                                                                                                                                            <input type="text" id="content" placeholder="例：外食、スーパーなど" autocomplete="off">
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                <div class="card">
                                                                                                                                                                                                                                                                                                    <div class="label">金額（円）</div>
                                                                                                                                                                                                                                                                                                        <input type="number" id="amount" placeholder="0" inputmode="numeric" pattern="[0-9]*">
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                          <div id="successView">
                                                                                                                                                                                                                                                                                                            <div class="success-icon">✅</div>
                                                                                                                                                                                                                                                                                                              <div class="success-text">登録しました！</div>
                                                                                                                                                                                                                                                                                                                <div class="success-sub">画面が閉じます</div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                <div class="footer-bar" id="footerBar">
                                                                                                                                                                                                                                                                                                                  <button class="submit-btn" id="submitBtn" onclick="submitForm()">登録する</button>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                  <script>
                                                                                                                                                                                                                                                                                                                  const CATEGORIES = ${catJson};
                                                                                                                                                                                                                                                                                                                  const GAS_URL = '${GAS_URL}';
                                                                                                                                                                                                                                                                                                                  let currentMonth = ${currentMonth};
                                                                                                                                                                                                                                                                                                                  let selectedPayment = '';
                                                                                                                                                                                                                                                                                                                  liff.init({ liffId: '${LIFF_ID}' }).catch(err => console.warn('LIFF init error:', err));
                                                                                                                                                                                                                                                                                                                  function changeMonth(delta) {
                                                                                                                                                                                                                                                                                                                    currentMonth = Math.min(12, Math.max(1, currentMonth + delta));
                                                                                                                                                                                                                                                                                                                      document.getElementById('monthDisplay').textContent = currentMonth + '月';
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                      function onCategoryChange() {
                                                                                                                                                                                                                                                                                                                        const sel = document.getElementById('category');
                                                                                                                                                                                                                                                                                                                          const opt = sel.options[sel.selectedIndex];
                                                                                                                                                                                                                                                                                                                            const needsPayment = opt && opt.dataset.needsPayment === 'true';
                                                                                                                                                                                                                                                                                                                              document.getElementById('paymentCard').style.display = needsPayment ? 'block' : 'none';
                                                                                                                                                                                                                                                                                                                                selectedPayment = '';
                                                                                                                                                                                                                                                                                                                                  document.getElementById('btn-cash').classList.remove('active');
                                                                                                                                                                                                                                                                                                                                    document.getElementById('btn-card').classList.remove('active');
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                    function selectPayment(type) {
                                                                                                                                                                                                                                                                                                                                      selectedPayment = type;
                                                                                                                                                                                                                                                                                                                                        document.getElementById('btn-cash').classList.toggle('active', type === 'キャッシュ');
                                                                                                                                                                                                                                                                                                                                          document.getElementById('btn-card').classList.toggle('active', type === 'カード');
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                          async function submitForm() {
                                                                                                                                                                                                                                                                                                                                            const category = document.getElementById('category').value;
                                                                                                                                                                                                                                                                                                                                              const content = document.getElementById('content').value.trim();
                                                                                                                                                                                                                                                                                                                                                const amount = document.getElementById('amount').value;
                                                                                                                                                                                                                                                                                                                                                  const needsPayment = document.getElementById('paymentCard').style.display !== 'none';
                                                                                                                                                                                                                                                                                                                                                    if (!category) { alert('項目を選択してください'); return; }
                                                                                                                                                                                                                                                                                                                                                      if (!content) { alert('内容を入力してください'); return; }
                                                                                                                                                                                                                                                                                                                                                        if (amount === '' || isNaN(Number(amount)) || Number(amount) < 0) { alert('金額を入力してください'); return; }
                                                                                                                                                                                                                                                                                                                                                          if (needsPayment && !selectedPayment) { alert('支払方法を選択してください'); return; }
                                                                                                                                                                                                                                                                                                                                                            const btn = document.getElementById('submitBtn');
                                                                                                                                                                                                                                                                                                                                                              btn.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                btn.textContent = '送信中...';
                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                      await fetch(GAS_URL, {
                                                                                                                                                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                  mode: 'no-cors',
                                                                                                                                                                                                                                                                                                                                                                                        headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                              body: JSON.stringify({ source: 'liff', month: currentMonth + '月', category, content, amount: Number(amount), paymentMethod: selectedPayment })
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                        alert('通信エラーが発生しました。再度お試しください。');
                                                                                                                                                                                                                                                                                                                                                                                                            btn.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                btn.textContent = '登録する';
                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                        const lines = ['✅ 家計簿登録完了', '月：' + currentMonth + '月', '項目：' + category, '内容：' + content, '金額：' + Number(amount).toLocaleString() + '円'];
                                                                                                                                                                                                                                                                                                                                                                                                                          if (selectedPayment) lines.push('支払：' + selectedPayment);
                                                                                                                                                                                                                                                                                                                                                                                                                            if (liff.isInClient()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                try { await liff.sendMessages([{ type: 'text', text: lines.join('\\n') }]); } catch (e) { console.warn('sendMessages error:', e); }
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('mainForm').style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById('footerBar').style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('successView').style.display = 'flex';
                                                                                                                                                                                                                                                                                                                                                                                                                                          setTimeout(() => { if (liff.isInClient()) liff.closeWindow(); }, 1800);
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                          </` + `script>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </html>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
--f5a77a1cb374caa5bad2b406c76afbbb97a27d8f2f585110aa62f4774ad6--
